### PR TITLE
Use helmfile.d feature

### PR DESCRIPTION
**Pull request by alebabai**
## what
Use `helmfile.d` feature to decompose `helmfile.yaml`

## why
#157

### CODE REVIEW

**Comment by alebabai** [comment]
It seems to me that helmfile don't see helmfile.d folder by default
https://github.com/roboll/helmfile/pull/160#issuecomment-402453737

**Comment by alebabai** [comment]
@osterman also i decomposed charts by _component_ label. What do you think about this idea?

**Comment by osterman** [comment]
Let's stick each chart in it's own helmfile because it allows people to easily overwrite a single file

**Comment by osterman** [comment]
it's a good idea to use the `01.` and `02.` prefix, but it's also good to separate them by some gap. this allows changing the order without needing to renumber all files.

**Comment by alebabai** [comment]
> Let's stick each chart in it's own helmfile because it allows people to easily overwrite a single file
ok, got it.

> it's a good idea to use the 01. and 02. prefix, but it's also good to separate them by some gap. this allows changing the order without needing to renumber all files.
Didn't quite catch what you meant.
Do you prefer to use something like this `01_portal.yaml` or just add number if it realy needed?

**Comment by osterman** [comment]
Yes, I think your screenshot captures it. We want some gaps so it's less painful to move things around.

**Pull request merged**
