### PR TITLE
Fix path to small-logo

### PR DESCRIPTION
**Pull request by osulli**
# What

- Removes `docs/` from path to small logo

# Why

- Path was invalid so image was broken

### CODE REVIEW

**Comment by osterman** [comment]
Can you confirm `make readme` is not affected?

**Comment by osulli** [comment]
I can `make readme` and all these unexpected changes appear @osterman

**Comment by osulli** [comment]
I understand the changes now and why they came about.
I also fixed an issue where even though the relative path was correct, since it was being imported into another .md file the relativity was wrong... so I just use the URL now.

@osterman

**Comment by osterman** [comment]
Thanks @osulli !

**Comment by osterman** [comment]
@osulli looks like we have an issue with one of our upstream packages related to some recent work to parallelize builds in `cloudposse/packages`. I'll get that fixed.

**Pull request merged**
