### PR TITLE
Bump terraform version to 0.10.1

### PR DESCRIPTION
**Pull request by comeanother**
## What

* Bump terraform version to 0.10.1

## Why

* Get ability to use latest terraform features

### CODE REVIEW

**Comment by osterman** [comment]
image

**Comment by comeanother** [comment]
@osterman should we do `rebase` instead of `merge` from master?

**Comment by osterman** [comment]
Yes - you are right. Generally we should do a rebase against master. I just hit the update button which does a merge, but that is not ideal.

**Comment by comeanother** [comment]
Tagged `0.3.0`

**Pull request merged**
