### PR TITLE
feat: add bindfs to support linux users. Fixes #594

### LINKED ISSUE #594: Files Written to Mounted Linux Home Directory Owned by Root User
## what
* The user's shell inside Geodesic runs as `root`
* The script that launches Geodesic bind-mounts the host user's `$HOME` to `/localhost` to provide access to configuration files and allow for editing of host files
* Depending on the storage driver being used, it is possible that files created under `/localhost` from within Geodesic will be set to the same owner UID and GID (that is, owned by `root`) on the host as they have within Geodesic.
* Notably, this is _**not an issue**_ with Docker Desktop for Mac, which uses the `osxfs` storage driver to maintain a distinction between the UID and GID of a file as seen from within the Docker container versus what is set on the host file system. See [Ownership](https://web.archive.org/web/20190719101305/https://docs.docker.com/docker-for-mac/osxfs/#ownership) section of documentation.
* Update Feb 2022: this is _**not an issue**_ with Docker v20 on Ubuntu (tested on 20.04 LTS) when running in [rootless mode](https://docs.docker.com/engine/security/rootless/). As with macOS, this configuration correctly translates file ownership between the root UID and GID inside the container to the user's UID and GID on the host. 

## remediation discussion

Under MacOS, this is not a problem because the [OSXFS](https://docs.docker.com/docker-for-mac/osxfs/#ownership) driver handles UID and GID remapping automatically.

Under Linux, it is possible to use [User Namespaces](https://docs.docker.com/engine/security/userns-remap/) to remap the root user UID 0 to another UID (presumably the UID of the user running Geodesic), and do the same for GID, however, the documentation says you cannot use remapping when using the `--privileged` flag, which Geodesic requires, and even if you could, it would cause problems with `sudo` and setuid binaries in the container. 

#### further reading

- https://docs.docker.com/engine/security/userns-remap/
- https://blog.gougousis.net/file-permissions-the-painful-side-of-docker/
- https://seravo.fi/2019/align-user-ids-inside-and-outside-docker-with-subuser-mapping

### LINKED ISSUE #766: Entering Bash Subshell Results in Functions in `prompt.sh` and Prompt Hooks Not Being Found
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
Spawning an interactive subshell via `bash` results in a broken command line prompt and other errors.

**[Edit:** _yes, that is how Geodesic works. To spawn an interactive subshell, use_ `bash -l`**]**

## Steps to Reproduce
1. Enter Geodesic
2. Enter subshell via `bash`

## Expected Behavior

Functions in `prompt.sh` and prompt hooks should be properly sourced when entering a subshell, however bash complains about functions in `prompt.sh` and prompt hooks not being found (see below).

## Screenshots / Logs

(without a valid kubeconfig set via `KUBECONFIG`)

```bash
 ✗ . [none] (HOST) geodesic ⨠ 
 ⧉  geodesic 
 ✗ . [none] (HOST) geodesic ⨠ bash
bash: _kube_ps1_update_cache: command not found
bash: prompter: command not found
  geodesic 
```

(with a valid kubeconfig set via `KUBECONFIG`)

```bash
 ✗ . [none] (HOST) geodesic ⨠
 ⧉  geodesic (eg-mgmt-uw2-sandbox:default)
 ✗ . [none] (HOST) geodesic ⨠ bash
bash: _kube_ps1_update_cache: command not found
bash: prompter: command not found
   geodesic (eg-mgmt-uw2-sandbox:default)
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX (host)
 - Geodesic Flavor: Alpine
 - Version `0.149.1`

## Additional Context

* Ran into this when attempting to reproduce #763

### LINKED ISSUE #767: Permissions of prompt:kube-ps1.sh causes issues with Linux operation as non-root user
## Describe the Bug
The permissions for `/etc/profile.d/prompt:kube-ps1.sh` as very restrictive.  This impacts #594.

## Steps to Reproduce
1. Execute `docker run -it --rm cloudposse/geodesic:latest-debian --login`
2. Execute:
```sh
 ⧉  geodesic 
 ✗ . [none] ~ ⨠ ls -l --color /etc/profile.d/prom*
-rwxrwxrwx 1 root root  7534 Jan 24 22:45 /etc/profile.d/prompt.sh
-rw------- 1 root root 10441 Jan  1  1970 /etc/profile.d/prompt:kube-ps1.sh
```

## Expected Behavior
All scripts should have similar permissions and not be restricted to just root

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux Mint 
 - Version 20.2 (uma) -- based on Ubuntu (focal)
 - Geodesic version 0.149.1 based on Debian GNU/Linux 10 (buster) (10.11)

### PR DESCRIPTION
**Pull request by drmikecrowe**
## what && why
- Use BindFS to preserve file owner user and group for files created on host from within Geodesic. Closes #594. Supersedes and closes #710.
- Make all prompt scripts accessible to non-root user. Closes #767
- Allow interactive subshells without errors or misleading prompts. Closes #766 
- Improve host volume detection. Fixes error reported via Slack.

### CODE REVIEW

**Review by Nuru — CHANGES_REQUESTED** [review]
@drmikecrowe Thank you for this PR. 

There are a bunch of nitpicky things I want to change, and I will make the changes, I just need you to confirm that this approach does everything you need with respect to file ownership and permissions and allowing you to continue to run as root inside Geodesic.

**Comment by drmikecrowe** [comment]
Confirmed -- I'm using this in my build w/o an issue.

I'm happy to adapt for future PR's if you'll share the nit-picky stuff :)

**Comment by drmikecrowe** [comment]
@Nuru  -- just discovered you also might need to `rm -rf /localhost.from-docker` -- after reboot and restart, the container has the old `/localhost` leftover and it must be deleted in that start script

**Comment by Nuru** [comment]
@drmikecrowe @nitrocode @korenyoni @sboardwell Please try this version and verify it fixes the listed bugs to the extent you those bugs were bothering you, and report back.

**Comment by Nuru** [comment]
PR closed and released as v0.151.0-rc1. Please try it out and report back here.

**Comment by Nuru** [comment]
Release candidate v0.152.0-rc1 published, includes this PR and updates to Alpine and Debian versions.

**Comment by sboardwell** [comment]
@Nuru I have a MacBook now, sorry.

**Comment by drmikecrowe** [comment]
Startup shows:

```
# Mounting /home/mcrowe into container at localhost.bindfs
# Starting new infrastructure session from pinnsg/infrastructure:latest
# Exposing port 33045
# Launching with extra Docker args: --volume=/home/mcrowe/Programming/Pinnacle/infrastructure:/project --volume=/home/mcrowe/Programming/Pinnacle/infrastructure/../websites:/websites --volume=/home/mcrowe/.encrypted:/conf/.encrypted
########################################################################################            
# No filesystem is mounted at /localhost which l
```
Additionally, added `set -x` to the top and ran:

```sh
set -x
if [[ $SHLVL == 1 ]] && [[ -n $GEODESIC_HOST_UID ]] && [[ -n $GEODESIC_HOST_GID ]] \
        && [[ -n $GEODESIC_LOCALHOST ]] && df -a | grep -q " ${GEODESIC_LOCALHOST}\$"; then
```

output:
```
 ⧉  Pinnacle 
 ✗ . [none] ~ ⨠ /etc/profile.d/_20-localhost.sh 
++ [[ 2 == 1 ]]
 ⧉  Pinnacle 

```

Dockerfile:
```dockerfile
ARG VERSION=0.151.0-rc1
ARG OS=debian
ARG CLI_NAME=infrastructure

FROM cloudposse/geodesic:$VERSION-$OS

###
### NVM for Node
####################################################################
SHELL ["/bin/bash", "--login", "-i", "-c"]
ENV NVM_DIR="/usr/local/nvm"
RUN ( git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR" && \
        cd "$NVM_DIR" && \
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)` )
RUN source "$NVM_DIR/nvm.sh" && nvm install 14 && npm i -g npm npm-check-updates && npm i -g yarn
####################################################################

# Geodesic banner
ENV BANNER="Pinnacle"
RUN chmod 755 /etc/profile.d/*
COPY rootfs/ /
RUN rm -rf /localhost
WORKDIR /
```

```
❯ find rootfs/
rootfs/
rootfs/etc
rootfs/etc/profile.d
rootfs/etc/profile.d/project.sh
rootfs/etc/profile.d/nvm.sh
```
(`project.sh` is global aliases for everybody, etc)

**Comment by Nuru** [comment]
@drmikecrowe 

The files under `/etc/profile.d/` need to be `source`'d to be effective. The `[[ 2 == 1 ]]` prevents the script from running in a subshell. 

The problem you are having is likely due to you not running the new version of the wrapper script. So far I cannot find any source for the exact message
```
Mounting /home/mcrowe into container at localhost.bindfs
```
Prior to release 0.149.0 the wrapper message was simply
```
# Mounting ${local_home} into container
```
With 0.149.0 the message changed to 
```
# Mounting ${local_home} into container with workdir ${GEODESIC_HOST_CWD}
```

It looks to me like you are running your own customized version of the older wrapper. Please save a copy of your custom wrapper, update your wrapper with `make install`, and try again.

**Pull request merged**
