### PR TITLE
[fzf] Create symlink conditionally

### PR DESCRIPTION
**Pull request by osterman**
## what
* Fix error when attempting to create link twice

## why
* Entering into a subshell (e.g. with `assume-role`) would emit an error about the target already existing

### CODE REVIEW

**Comment by Nuru** [comment]
Why are we doing this instead of using `bash complete`?

**Comment by osterman** [comment]
Can you elaborate?

**Comment by Nuru** [comment]
If we use
```
complete -C '/usr/share/bash-completion/completions/fzf/fzf.sh' fzf
```
as we did [here](https://github.com/cloudposse/geodesic/blob/master/rootfs/etc/profile.d/aws.sh#L17-L20) it won't be a problem to run it twice. So if that works (and maybe it doesn't), I'd prefer that to linking only because it does not have the extra linking problem.

**Comment by osterman** [comment]
So my thinking was to leverage the existing `rc.d` config structure; that said, this might be a better way to do it.

**Comment by osterman** [comment]
> 
as we did [here](https://github.com/cloudposse/geodesic/blob/master/rootfs/etc/profile.d/aws.sh#L17-L20)

@Nuru good point. I'll update it.

**Comment by Nuru** [comment]
I'm in favor of `rc.d` structure when the installation is not conditional, but if it is going to be conditional then I prefer to set it in the shell rather than the file system.

**Comment by osterman** [comment]
> `complete -C '/usr/share/bash-completion/completions/fzf' fzf`

This works, but looks like there's some bigger issue. 

```
/usr/share/bash-completion/completions/fzf: line 34: bind: warning: line editing not enabled
/usr/share/bash-completion/completions/fzf: line 34: bind: warning: line editing not enabled
/usr/share/bash-completion/completions/fzf: line 34: bind: warning: line editing not enabled
/usr/share/bash-completion/completions/fzf: line 34: bind: warning: line editing not enabled

```

**Pull request merged**
