### PR TITLE
Fix utf-8 prompt

### PR DESCRIPTION
**Pull request by osterman**
## what
* Use special `bash` 3.2+ feature for outputting `utf8` characters (`$'\uXXXX'`)
* Explicitly set locale (sorry, hardcoded to `en_US.utf8`)

## why
* This seems to fix the prompt line wrapping problems
* `\[....\]` does not help with `utf8` characters (only `ansi`)

image

### CODE REVIEW

**Comment by osterman** [comment]
That looks like the cluster container was not rebuilt against the updated geodesic.

**Comment by osterman** [comment]
Confirm you see updated code for prompt.sh in your container

**Comment by comeanother** [comment]
>Confirm you see updated code for prompt.sh in your container

Confirmed
screenshot from 2017-10-02 12-41-59

**Comment by comeanother** [comment]
screenshot from 2017-10-18 19-13-12

**Comment by comeanother** [comment]
It happens when I try to navigate through the history with `arrow keys`
screenshot from 2017-10-18 19-14-53
screenshot from 2017-10-18 19-15-48

**Comment by comeanother** [comment]
But CLI looks stable now.
There is no characters overlay when using long commands or reverse search with `Ctrl+R` noticed.

**Comment by comeanother** [comment]
Looks like `red cross` and `white check mark` are missing.
screenshot from 2017-10-18 19-22-19

**Comment by comeanother** [comment]
White check mark is present in both cases (role assumed, role not assumed)
screenshot from 2017-10-30 16-26-31

**Comment by comeanother** [comment]
Now it works well, for first login to geodesic
screenshot from 2017-10-30 16-58-37

**Comment by comeanother** [comment]
But it doesn't work for `leave-role`.

**Comment by comeanother** [comment]
Unable to unset `AWS_SESSION_TTL`.
screenshot from 2017-10-30 17-56-04

**Comment by comeanother** [comment]
Fixed red cross.
screenshot from 2017-10-30 18-27-27

**Comment by comeanother** [comment]
Weird error occurred in Travis
screenshot from 2017-10-31 09-08-00

**Pull request merged**
